---
- name: Create etcd cert directory
  ansible.builtin.file:
    path: "{{ etcd_cert_dir }}"
    state: directory
    mode: '0750'
  when:
    - inventory_hostname  in groups['kube_control_plane']

- name: Generate symlink to etcd certs
  ansible.builtin.file:
    src: "{{ etcd_cert_paths.client[item.src] }}"
    dest: "{{ etcd_cert_dir }}/{{ item.dest }}"
    state: link
    force: true
  loop:
    - src: ca
      dest: "{{ kube_etcd_cacert_file }}"
    - src: cert
      dest: "{{ kube_etcd_cert_file }}"
    - src: key
      dest: "{{ kube_etcd_key_file }}"
  when:
    - inventory_hostname  in groups['kube_control_plane']
